### ISSUE TITLE
add option to create a database if certain vars are provided

### ISSUE THREAD

**Issue by Sandalorian** [sirReeall/mysql#3]
It should be possible to create a database using this role.
This will require that some variables are provided when running the role. 
For example:

```yaml
    - include_role: 
        name: sirreeall.mysql
      vars:
        mysql_root_password: "{{ db_password }}"
        create_db: "footballTeam"
        create_db_user: "teamManager"
```
